---
- name: Delegate playbook
  become: yes
  hosts: all

  vars:
   mytext: "Privet Tissa"

  tasks:
  - name: Ping tst
    ping:

  - name: Unregister Server from Load Balancer
    shell: echo This server {{ inventory_hostname }} was deregistered from our Load Balancer, node name is {{ ansible_nodename }} >> /home/log.txt
    delegate_to: 127.0.0.1
  
  - name: Update My DB
    shell: echo "0000000000000 updating db"
    run_once: true
 
  - name: Create file1
    copy:
      dest: /home/file1.txt
      content: |
         This is file1
         On Eng - Hello Tissa
         On Rus - {{ mytext }}
    delegate_to: linux2

  - name: Create file2
    copy:
      dest: /home/file2.txt
      content: |
          This is file2
          On Eng - Hello Tissa
          On Rus - {{ mytext }}


#  - name: Reboot my servers
 #   shell: sleep 3 && reboot now
  #  async: 1
   # poll: 0

 # - name: Wait till my servers will come up online
  #  wait_for:
   #     host: "{{ inventory_hostname }}"
    #    state: started
     #   delay: 5
      #  timeout: 40
   # delegate_to: 127.0.0.1
