---

- name: Install Apache and upload My Web Page
  hosts: all
  become: yes
  
  vars:
    source_file: ./MyWebSite/index.html
    media_file1: ./MyWebSite/me.jpg
    media_file2: ./MyWebSite/tissa.JPG
    media_file3: ./MyWebSite/she.jpg
    destin_file: /var/www/html
 
  tasks:
  - name: Check Linux version
    debug: var=ansible_os_family

  - block:    # =======Block for RedHat=======


      - name: Install Apache WebServer for RedHat
        yum: name=httpd state=latest

      - name: Start Web Servers and automatic startup for RedHat
        service: name=httpd state=started enabled=yes
   
      - name: Copy MyHomePage to servers
       # copy: src={{ source_file }} dest={{ destin_file }} mode=555
       # copy: src={{ media_file1 }} dest={{ destin_file }} mode=555
       # copy: src={{ media_file2 }} dest={{ destin_file }} mode=555
        copy: src={{ item.src }} dest={{ item.dest }} mode=555
        with_items:
          - { src: '{{ source_file }}' , dest: '{{ destin_file }}'  }
          - { src: '{{ media_file1 }}' , dest: '{{ destin_file }}' }
          - { src: '{{ media_file2 }}' , dest: '{{ destin_file }}' }
          - { src: '{{ media_file3 }}' , dest: '{{ destin_file }}' }
        notify: Restart Apache RedHat

    when: ansible_os_family == "RedHat"

  - block: #===========Block for Debian======

      - name: Install Apache WebServer for Debian
        apt: name=apache2 state=latest

      - name: Copy MyHomePage to servers
        copy: src={{ item.src }} dest={{ item.dest }} mode=555
        with_items:
          - { src: '{{ source_file }}' , dest: '{{ destin_file }}'  }
          - { src: '{{ media_file1 }}' , dest: '{{ destin_file }}' }
          - { src: '{{ media_file2 }}' , dest: '{{ destin_file }}' }
          - { src: '{{ media_file3 }}' , dest: '{{ destin_file }}' }
        notify: Restart Apache Debian

      - name: Start Web Servers and automatic startup for Debian
        service: name=apache2 state=started enabled=yes
   
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
  
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
