---
- name: Install default Apache Web Server
  hosts: PROD_SERVERS
  become: yes

  tasks:
  - name: Install Apache Web Server
    yum:  name=httpd state=latest
  

  - name: Start Apache and Enable automatic startup
    service: name=httpd state=started enabled=yes

